### PR TITLE
DRAFT Rebase onto upstream master at 22f19c4 (0.7.2 when released)

### PR DESCRIPTION
**Pull request by Undef-a**
Currently untested, but compiles. This should allow use of v2 groups and a few other changes, though it will have to be built into purple-signal as well. 

I apologise for integrating the `String` to `File` change into your last commit. This was an error on my part, but I couldn't bring myself to go back through the rebase and bug search process again to fix it. 

EDIT: tested on pidgin/pinephone. Everything that was previously working works.

### CODE REVIEW

**Comment by hoehermann** [comment]
Looks like we both made mistakes. After merging your pull request, I messed up the signal-cli fork on github and locally. I undid the changes to the repository, but github still displays it as "merged". This is the first project I am working with submodules, so please bear with me. I want to look into it again in the coming days. I am grateful for your work as I really did not want to resolve all the conflicts. And I have no idea about what to do with the new group data store, yet.

**Comment by Undef-a** [comment]
Submodules aren't easy. Usually treating them as their own repo entirely then committing in the parent when you're happy is the best way to go, but that does mean that for every merge here, you have another one over there to do, including adding one on top of things like that PR. 

Would you like me to open a new PR? Otherwise, you should be able to add my repo as a remote and manually pull. You will probably want to do this one first anyway, so the main repo has something to point to.

There were a lot of conflicts, but most of them followed the same pattern. Once I got that, the rest of it was pretty easy. Only two or three places where it differed enough that I had to work out what both sides wanted. But none of that implements the new groups. Those are probably going to have to be plumbed through the same way the old groups already are. 

Thanks for looking into it.

**Comment by hoehermann** [comment]
I just realized that this rebases not onto 0.7.1, but on upstream's master (0.7.1 plus new commits). You wrote that in the PR description, but I failed to understand what that meant. Sorry for the confusion.

> Would you like me to open a new PR?

Yes. Please either rebase onto 0.7.1 (83d5d53) or wait for the next release (0.7.2 I guess) and then rebase onto that one. I want end-users to use a released version so they do not need to build signal-cli. I had the official 0.7.1 release in my system which stops the build from succeeding. :(

**Comment by Undef-a** [comment]
Considering the main change in this rebase is dealing with the String -> File change in the API, It's probably best to leave this in draft mode until 0.7.2 comes out. Judging by the last few releases, that won't take too long anyway.

**Comment by hoehermann** [comment]
signal-cli 0.7.2 has been released. I rebased onto your work. I am resolved the conflicts locally and pushed the new version. Thank you. :)

**Pull request closed without merging**
